app/models.py
from app import db, login_manager
from flask_login import UserMixin


login_manager.login_view = 'main.login'

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), unique=True, nullable=False)
    email = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(350), nullable=False)

    def __repr__(self):
        return f"<user {self.name}, {self.email}>"
    
    def asdict(self):
        return {
            'id':self.id,
            'name':self.name,
            'email':self.email,
        }  

    Avista = db.relationship('Avista', backref=('user'), lazy=True)
    Financia = db.relationship('Financia', backref=('user'), lazy=True)


class Avista(db.Model):
    __tablename__ = 'avista'
    
    id = db.Column(db.Integer, primary_key=True)
    
    name = db.Column(db.String(150), nullable=False)
    name_vehicle = db.Column(db.String(150), nullable=False)
    value_vehicle = db.Column(db.Float, nullable=False)
    value_prohibited = db.Column(db.Float, nullable=False) 
    
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f'<avista {self.name}, {self.email}>'
    
    def asdict(self):
        return {
            'id':self.id,
            'name':self.name,
            'name_vehicle':self.name_vehicle,
            'value_vehicle':self.value_vehicle,
            'value_prohibited':self.value_prohibited,
            'user_id':self.user_id
        }


class Financia(db.Model):
    __tablename__ = 'financiamento'

    id = db.Column(db.Integer, primary_key=True)

    name = db.Column(db.String(150), nullable=False)
    name_vehicle = db.Column(db.String(150), nullable=False)
    value_vehicle = db.Column(db.Float, nullable=False)
    value_prohibited = db.Column(db.Float, nullable=False) 
    installments = db.Column(db.Integer, nullable=False)
    
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f'<financia {self.name}, {self.email}>'
    
    def asdict(self):
        return {
            'id':self.id,
            'name':self.name,
            'name_vehicle':self.name_vehicle,
            'value_vehicle':self.value_vehicle,
            'value_prohibited':self.value_prohibited,
            'installments':self.installments,
            'user_id':self.user_id
        }


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from dotenv import load_dotenv
import os


load_dotenv()
db = SQLAlchemy()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    app.config['SQLALHCEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')

    db.init_app(app)
    login_manager.init_app(app)

    from .routes import main
    app.register_blueprint(main)

    with app.app_context():
        db.create_all()

    return app

app/routes.py
from flask import render_template, request, redirect, url_for, session, Blueprint
from flask_login import login_required, current_user, login_user
from app import db
from .models import User, Avista, Financia
from werkzeug.security import generate_password_hash, check_password_hash
from time import sleep


main = Blueprint('main', __name__)

# Rota para página principal
@main.route('/')
def home():
    return render_template('index.html')

# Rota para página de cadastro e login
@main.route('/register')
def register():
    return render_template('register.html')

# Rota para página para cadastrar clientes
@main.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html')

# Rota para página para ver os clientes cadastrados
@main.route('/view_clientes')
@login_required
def view_clientes():
    financia_users = Financia.query.filter_by(user_id=current_user.id).all()
    avista_users = Avista.query.filter_by(user_id=current_user.id).all()

    users = financia_users + avista_users

    return render_template('view_users.html', users=users)

# Rota para fazer cadastro
@main.route('/get_user_cadastro', methods=['POST', 'GET'])
def get_user_cadastro():
    error_message = None

    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')

        user_exists = User.query.filter((User.name == name) | (User.email == email)).first()

        if user_exists:
            error_message = 'Nome ou Email já cadastrado!'
            return render_template('register.html', error_cadastro=error_message)
        else:
            hash_password = generate_password_hash(password)
            
            user = User(name=name, email=email, password=hash_password)

            db.session.add(user)
            db.session.commit()

            sleep(3)

            return redirect(url_for('main.dashboard'))
        
    return render_template('register.html')

# Rota para fazer login
@main.route('/get_user_login', methods=['POST', 'GET'])
def get_user_login():
    error_message = None

    if request.method == 'POST':
        name = request.form.get('name_login')
        email = request.form.get('email_login')
        password = request.form.get('password_login')

        user_exists = User.query.filter(User.name == name, User.email == email).first()

        if user_exists and check_password_hash(user_exists.password, password):
            login_user(user_exists)

            sleep(3)

            return redirect(url_for('main.dashboard'))
        else:
            error_message = 'Dados inválidos!'
            return render_template('register.html', error_login=error_message)
        
    return render_template('register.html')

# Rota para cadastrar um cliente avista
@main.route('/get_user_avista', methods=['POST', 'GET'])
@login_required
def user_get_avista():
    if request.method == 'POST':
        name = request.form.get('name_avista')
        name_vehicle = request.form.get('name_vehicle_avista')
        value_vehicle = request.form.get('value_vehicle_avista')
        value_prohibited = request.form.get('value_prohibited_avista')

        new_info = Avista(name=name, name_vehicle=name_vehicle, value_vehicle=value_vehicle, value_prohibited=value_prohibited, user_id=current_user.id)
        
        db.session.add(new_info)
        db.session.commit()

        sleep(3)

        return redirect(url_for('main.dashboard'))
    
    return render_template('dashboard.html')

# Rota para cadastrar cliente financiamento
@main.route('/get_user_financia', methods=['POST', 'GET'])
@login_required
def get_user_financia():
    if request.method == 'POST':
        name = request.form.get('name')
        name_vehicle = request.form.get('name_vehicle')
        value_vehicle = request.form.get('value_vehicle')
        value_prohibited = request.form.get('value_prohibited')
        installments = request.form.get('installments')

        new_info = Financia(name=name, name_vehicle=name_vehicle, value_vehicle=value_vehicle, value_prohibited=value_prohibited, installments=installments, user_id=current_user.id)

        db.session.add(new_info)
        db.session.commit()

        sleep(3)

        return redirect(url_for('main.dashboard'))
    
    return render_template('dashboard.html')

app/templates/dashboard.html
<!DOCTYPE html>

<html lang="pt-br">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>
    <link rel="stylesheet" href="../static/css/dashboard.css">

</head>

<body>

    <div class="container">

        <div class="content" id="content">

            <div class="avista" id="avista">

                <h1>Cliente</h1>
                <h1>Avista</h1>

                <form action="/get_user_avista" method="POST" autocomplete="off">

                    <div class="row">
                        <input type="text" name="name_avista" id="name_avista" required minlength="3" placeholder=" ">
                        <label for="name_avista">Nome do Cliente</label>
                    </div>

                    <div class="row">
                        <input type="text" name="name_vehicle_avista" id="name_vehicle_avista" required minlength="3" placeholder=" ">
                        <label for="name_vehicle_avista">Nome do Veiculo</label>
                    </div>

                    <div class="row">
                        <input type="number" name="value_vehicle_avista" id="value_vehicle_avista" required minlength="3" placeholder=" ">
                        <label for="value_vehicle_avista">Valor do Veiculo</label>
                    </div>

                    <div class="row">
                        <input type="number" name="value_prohibited_avista" id="value_prohibited_avista" required minlength="3" placeholder=" ">
                        <label for="value_prohibited_avista">Valor de Entrada</label>
                    </div>

                    <p>Deseja cadastrar um cliente de financiamento? <a href="#" onclick="toggleForms()">Clique aqui</a></p>

                    <button id="btn_avista" onclick="get_spin_avista()">Cadastrar</button>

                    <div class="load" id="load_avista">

                        <button>
                            <div class="spin"></div>
                        </button>

                    </div>

                </form>

                <a href="{{ url_for('main.view_clientes') }}">
                    <button class="view_clientes" id="view_clientes" onclick="get_view_clientes()">Ver Clientes</button>
                </a>

            </div>

            <div class="financia" id="financia">

                <h1>Cliente</h1>
                <h1>Financiamento</h1>

                <form action="/get_user_financia" method="POST" autocomplete="off">

                    <div class="row">
                        <input type="text" name="name" id="name" required minlength="3" placeholder=" ">
                        <label for="name">Nome do Cliente</label>
                    </div>

                    <div class="row">
                        <input type="text" name="name_vehicle" id="name_vehicle" required minlength="3" placeholder=" ">
                        <label for="name_vehicle">Nome do Veiculo</label>
                    </div>

                    <div class="row">
                        <input type="number" name="value_vehicle" id="value_vehicle" required minlength="3" placeholder=" ">
                        <label for="value_vehicle">Valor do Veiculo</label>
                    </div>

                    <div class="row">
                        <input type="number" name="value_prohibited" id="value_prohibited" required minlength="3" placeholder=" ">
                        <label for="value_prohibited">Valor de Entrada</label>
                    </div>

                    <div class="row">
                        <input type="number" name="installments" id="installments" required minlength="2" placeholder=" ">
                        <label for="installments">Número de Parcelas</label>
                    </div>

                    <p>Deseja cadastrar um cliente avista? <a href="#" onclick="toggleForms()">Clique aqui</a></p>

                    <button id="btn_financia" onclick="get_spin_financia()">Cadastrar</button>

                    <div class="load" id="load_financia">

                        <button>
                            <div class="spin"></div>
                        </button>

                    </div>

                </form>

                <button class="view_clientes" id="view_clientes" onclick="get_view_clientes()">Ver Clientes</button>

            </div>

        </div>

    </div>

    <script src="../static/js/dashboard.js"></script>
    
</body>

</html>

app/templates/index.html
<!DOCTYPE html>

<html lang="pt-br">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Client Registration</title>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>
    <link rel="stylesheet" href="../static/css/index.css">

</head>

<body>

    <main>

        <header>

            <section class="logo">

                <img src="../static/imagens/logo.png" alt="Logo">

                <h1>Client Sans</h1>

            </section>

            <nav class="links">

                <ul>
                    <li><a href="#home">Home</a></li>
                    <li><a href="#about">About</a></li>
                </ul>

            </nav>

            <nav class="btn_log">

                <a href="{{ url_for('main.register') }}">
                    <button class="btn_cadastro">Cadastrar</button>
                </a>

                <a href="{{ url_for('main.register') }}">
                    <button class="btn_login">Login</button>
                </a>

            </nav>

        </header>

        <section class="home" id="home">

            <article>

                <h1>Client Sans</h1>

                <p>Gerencie clientes de forma simples e organizada. Cadastre novos usuários, edite informações, visualize a lista de clientes e mantenha o controle total dos dados com segurança e praticidade.</p>

                <nav>

                    <a href="{{ url_for('main.register') }}">
                        <button>Entrar</button>
                    </a>

                </nav>

            </article>

        </section>

    </main>
    
</body>

</html>

app/templates/register.html
<!DOCTYPE html>

<html lang="pt-br">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>
    <link rel="stylesheet" href="../static/css/register.css">

</head>

<body>

    <main class="container">

        <section class="content" id="content">

            <section class="cadastro" id="cadastro">

                <h1>Cadastro</h1>

                <form action="/get_user_cadastro" method="POST" autocomplete="off">

                    <div class="row">
                        <input type="text" name="name" id="name" required minlength="3" placeholder=" ">
                        <label for="name">Seu nome</label>
                    </div>
                    
                    <div class="row">
                        <input type="email" name="email" id="email" required minlength="12" placeholder=" ">
                        <label for="email">Seu email</label>
                    </div>

                    <div class="row">
                        <input type="password" name="password" id="password" required minlength="8" placeholder=" ">
                        <label for="password">Sua senha</label>
                    </div>

                    <p>Já tem uma conta? <a href="#" onclick="toggleForms()">LOGIN</a></p>

                    {% if error_cadastro %}
                        <div class="error">
                            <p>{{ error_cadastro }}</p>
                        </div>
                    {% endif %}

                    <button id="btn_cadastro" onclick="get_spin_cadastro()">Cadastro</button>

                    <div class="load" id="load_cadastro">

                        <button>

                            <div class="spin"></div>

                        </button>

                    </div>

                </form>

            </section>

            <section class="login" id="login">

                <h1>Login</h1>

                <form action="/get_user_login" method="POST" autocomplete="off">

                    <div class="row">
                        <input type="text" name="name_login" id="name_login" required minlength="3" placeholder=" ">
                        <label for="name_login">Seu nome</label>
                    </div>

                    <div class="row">
                        <input type="email" name="email_login" id="email_login" required minlength="12" placeholder=" ">
                        <label for="email_login">Seu email</label>
                    </div>

                    <div class="row">
                        <input type="password" name="password_login" id="password_login" required minlength="8" placeholder=" ">
                        <label for="password_login">Sua senha</label> 
                    </div>

                    <p>Não tem uma conta? <a href="#" onclick="toggleForms()">CADASTRO</a></p>

                    {% if error_login %}
                        <div class="error">
                            <p>{{ error_login }}</p>
                        </div>
                    {% endif %}

                    <button id="btn_login" onclick="get_spin_login()">Login</button>

                    <div class="load" id="load_login">

                        <button>

                            <div class="spin"></div>

                        </button>

                    </div>

                </form>

            </section>

        </section>

    </main>
    
    <script src="../static/js/register.js"></script>

</body>

</html>

app/templates/view_users.html
<!DOCTYPE html>

<html lang="pt-br">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Clientes</title>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>
    <link rel="stylesheet" href="../static/css/view_clientes.css">

</head>

<body>
    
    <div class="container">

        <div class="avista">

            <h1>Avista</h1>

            {% for user in users %}

                <div class="users">

                    <ul>
                        <li>{{ user.name }}</li>
                        <li>{{ user.name_vehicle }}</li>
                        <li>{{ user.value_vehicle }}</li>
                        <li>{{ user.value_prohibited }}</li>
                    </ul>

                    <ul>
                        <li></li>
                    </ul>

                </div>

            {% endfor %}

        </div>

        <div class="financia">

            <h1>Financiamento</h1>

        </div>

    </div>

</body>

</html>